#!/usr/bin/env bash
# create-prerequisites.sh
# Generated by azure-api-tester skill — REVIEW BEFORE RUNNING
#
# STRUCTURE
#   A  Parent resources   (Tier 1 — required, uncommented, safe to run)
#   B  Payload-linked     (Tier 2 — likely needed, COMMENTED OUT by default)
#   C  Manual steps       (Tier 4 — cannot be automated, instructions only)
#
# USAGE
#   1. Review every command, especially Section B
#   2. Set environment variables below or export them before running
#   3. Uncomment Tier 2 blocks you actually need
#   4. Run:  bash create-prerequisites.sh
#   5. Copy the printed --param flags into your azure-api-tester command
# ---------------------------------------------------------------------------

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration — set these or export them before running the script
# ---------------------------------------------------------------------------
SUBSCRIPTION_ID="${SUBSCRIPTION_ID:-$(az account show --query id -o tsv)}"
LOCATION="${LOCATION:-eastus}"
RG_NAME="${RG_NAME:-<resource-group-name>}"

# API-specific names — fill in values appropriate for the API under test
# WORKSPACE_NAME="${WORKSPACE_NAME:-<workspace-name>}"
# ACCOUNT_NAME="${ACCOUNT_NAME:-<account-name>}"

echo "Subscription : $SUBSCRIPTION_ID"
echo "Location     : $LOCATION"
echo "Resource group: $RG_NAME"
echo ""

# ---------------------------------------------------------------------------
# A  PARENT RESOURCES — Tier 1 (required, uncommented)
# Uncomment the block(s) that match the parent resources in the API URI path.
# ---------------------------------------------------------------------------
echo "=== A: Creating parent resources (Tier 1) ==="

az group create \
  --name "$RG_NAME" \
  --location "$LOCATION" \
  --output table

# --- ML Workspace  (/workspaces/{workspaceName}) ---
# az ml workspace create \
#   --name "$WORKSPACE_NAME" \
#   --resource-group "$RG_NAME" \
#   --location "$LOCATION" \
#   --output table

# --- Cognitive Services Account  (/accounts/{accountName}) ---
# az cognitiveservices account create \
#   --name "$ACCOUNT_NAME" \
#   --resource-group "$RG_NAME" \
#   --kind "OpenAI" \
#   --sku "S0" \
#   --location "$LOCATION" \
#   --output table

# --- Container Registry  (/registries/{registryName}) ---
# ACR_NAME="${ACR_NAME:-<registry-name>}"
# az acr create \
#   --name "$ACR_NAME" \
#   --resource-group "$RG_NAME" \
#   --sku Basic \
#   --output table

echo ""

# ---------------------------------------------------------------------------
# B  PAYLOAD-LINKED RESOURCES — Tier 2 (likely needed, COMMENTED OUT)
# Enable a block only if the API payload requires that resource ID and you
# do not already have an existing one to reference.
# ---------------------------------------------------------------------------
echo "=== B: Payload-linked resources (Tier 2 — skipped by default, see comments) ==="

# --- Storage Account (storageAccountId / storageId) ---
# Enable this block if the API payload contains storageAccountId / storageId.
# STORAGE_NAME="${STORAGE_NAME:-<storage-account-name>}"
# az storage account create \
#   --name "$STORAGE_NAME" \
#   --resource-group "$RG_NAME" \
#   --location "$LOCATION" \
#   --sku Standard_LRS \
#   --kind StorageV2 \
#   --output table
# STORAGE_ID=$(az storage account show \
#   --name "$STORAGE_NAME" \
#   --resource-group "$RG_NAME" \
#   --query id -o tsv)
# export STORAGE_ID
# echo "Storage Account ID: $STORAGE_ID"

# --- Key Vault (keyVaultId / key_vault_id) ---
# Enable this block if the API payload contains keyVaultId.
# KV_NAME="${KV_NAME:-<key-vault-name>}"
# az keyvault create \
#   --name "$KV_NAME" \
#   --resource-group "$RG_NAME" \
#   --location "$LOCATION" \
#   --output table
# KV_ID=$(az keyvault show \
#   --name "$KV_NAME" \
#   --resource-group "$RG_NAME" \
#   --query id -o tsv)
# export KV_ID
# echo "Key Vault ID: $KV_ID"

# --- Application Insights (applicationInsightsId) ---
# Enable this block if the API payload contains applicationInsightsId.
# AI_NAME="${AI_NAME:-<app-insights-name>}"
# az monitor app-insights component create \
#   --app "$AI_NAME" \
#   --location "$LOCATION" \
#   --resource-group "$RG_NAME" \
#   --output table
# AI_ID=$(az monitor app-insights component show \
#   --app "$AI_NAME" \
#   --resource-group "$RG_NAME" \
#   --query id -o tsv)
# export AI_ID
# echo "App Insights ID: $AI_ID"

# --- Container Registry (containerRegistryId) ---
# Enable this block if the API payload contains containerRegistryId.
# ACR_NAME="${ACR_NAME:-<registry-name>}"
# az acr create \
#   --name "$ACR_NAME" \
#   --resource-group "$RG_NAME" \
#   --sku Basic \
#   --output table
# ACR_ID=$(az acr show \
#   --name "$ACR_NAME" \
#   --resource-group "$RG_NAME" \
#   --query id -o tsv)
# export ACR_ID
# echo "Container Registry ID: $ACR_ID"

# --- Virtual Network + Subnet (subnetId) ---
# Enable this block if the API payload contains subnetId.
# VNET_NAME="${VNET_NAME:-<vnet-name>}"
# SUBNET_NAME="${SUBNET_NAME:-default}"
# az network vnet create \
#   --name "$VNET_NAME" \
#   --resource-group "$RG_NAME" \
#   --location "$LOCATION" \
#   --address-prefix "10.0.0.0/16" \
#   --subnet-name "$SUBNET_NAME" \
#   --subnet-prefix "10.0.0.0/24" \
#   --output table
# SUBNET_ID=$(az network vnet subnet show \
#   --vnet-name "$VNET_NAME" \
#   --name "$SUBNET_NAME" \
#   --resource-group "$RG_NAME" \
#   --query id -o tsv)
# export SUBNET_ID
# echo "Subnet ID: $SUBNET_ID"

echo ""

# ---------------------------------------------------------------------------
# C  MANUAL STEPS — Tier 4 (cannot be automated — instructions only)
# Supply these values manually via --param or config.yml after gathering them.
# ---------------------------------------------------------------------------
echo "=== C: Manual steps required ==="
echo ""
echo "  The following values cannot be created by this script."
echo "  Gather them and pass via --param or add to ~/.azure-api-tester.yaml:"
echo ""
echo "  MANUAL: userAssignedIdentityId"
echo "    az identity show --name <name> --resource-group $RG_NAME --query id -o tsv"
echo ""
echo "  MANUAL: Secrets / access keys / connection strings"
echo "    Retrieve from Azure Portal or Key Vault after all resources are created."
echo ""

# ---------------------------------------------------------------------------
# Summary — copy the relevant --param flags to your azure-api-tester command
# ---------------------------------------------------------------------------
echo ""
echo "=== Done. Pass these --param flags to azure-api-tester ==="
echo ""
echo "  --param subscriptionId=$SUBSCRIPTION_ID"
echo "  --param resourceGroupName=$RG_NAME"
# Uncomment and add lines for any Tier 2 IDs you captured above, e.g.:
# echo "  --param storageAccountId=$STORAGE_ID"
# echo "  --param keyVaultId=$KV_ID"
echo ""
echo "Example:"
echo "  azure-api-tester test \"<DOCS_URL>\" --param resourceGroupName=$RG_NAME ..."
